### ISSUE TITLE
8.1.0beta3: Deprecated: Return type of parallel\Events::count() should either be compatible with Countable::count(): int

### ISSUE THREAD

**Issue by WyriHaximus** [krakjoe/parallel#217]
When having this extension loaded with #216 applied the following error shows up when running PHP: 

```
Deprecated: Return type of parallel\Events::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
```

**Comment by cmb69** [comment]
Something like the following (untested) should fix this issue:
````.diff
 src/events.c | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/src/events.c b/src/events.c
index ceb2552..4708890 100644
--- a/src/events.c
+++ b/src/events.c
@@ -230,6 +230,9 @@ PHP_METHOD(Events, poll)
     php_parallel_events_poll(events, return_value);
 }
 
+ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(php_parallel_events_count_arginfo, 0, 0, IS_LONG, 0)
+ZEND_END_ARG_INFO()
+
 PHP_METHOD(Events, count)
 {
     php_parallel_events_t *events = php_parallel_events_from(getThis());
@@ -247,7 +250,7 @@ zend_function_entry php_parallel_events_methods[] = {
     PHP_ME(Events, setBlocking, php_parallel_events_set_blocking_arginfo, ZEND_ACC_PUBLIC)
     PHP_ME(Events, setTimeout,  php_parallel_events_set_timeout_arginfo, ZEND_ACC_PUBLIC)
     PHP_ME(Events, poll,        php_parallel_events_poll_arginfo, ZEND_ACC_PUBLIC)
-    PHP_ME(Events, count,       php_parallel_no_args_arginfo, ZEND_ACC_PUBLIC)
+    PHP_ME(Events, count,       php_parallel_events_count_arginfo, ZEND_ACC_PUBLIC)
     PHP_FE_END
 };
 
````

**Comment by dividerbeam** [comment]
> Something like the following (untested) should fix this issue:
> 
> ```diff
>  src/events.c | 5 ++++-
>  1 file changed, 4 insertions(+), 1 deletion(-)
> 
> diff --git a/src/events.c b/src/events.c
> index ceb2552..4708890 100644
> --- a/src/events.c
> +++ b/src/events.c
> @@ -230,6 +230,9 @@ PHP_METHOD(Events, poll)
>      php_parallel_events_poll(events, return_value);
>  }
>  
> +ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(php_parallel_events_count_arginfo, 0, 0, IS_LONG, 0)
> +ZEND_END_ARG_INFO()
> +
>  PHP_METHOD(Events, count)
>  {
>      php_parallel_events_t *events = php_parallel_events_from(getThis());
> @@ -247,7 +250,7 @@ zend_function_entry php_parallel_events_methods[] = {
>      PHP_ME(Events, setBlocking, php_parallel_events_set_blocking_arginfo, ZEND_ACC_PUBLIC)
>      PHP_ME(Events, setTimeout,  php_parallel_events_set_timeout_arginfo, ZEND_ACC_PUBLIC)
>      PHP_ME(Events, poll,        php_parallel_events_poll_arginfo, ZEND_ACC_PUBLIC)
> -    PHP_ME(Events, count,       php_parallel_no_args_arginfo, ZEND_ACC_PUBLIC)
> +    PHP_ME(Events, count,       php_parallel_events_count_arginfo, ZEND_ACC_PUBLIC)
>      PHP_FE_END
>  };
>  
> ```

this changes make other errors:

root@converter:~/parallel# make test
/bin/bash /root/parallel/libtool --mode=compile cc -I. -I/root/parallel -I/root/parallel/include -I/root/parallel/main -I/root/parallel -I/root/bin/php-latest/include/php -I/root/bin/php-latest/include/php/main -I/root/bin/php-latest/include/php/TSRM -I/root/bin/php-latest/include/php/Zend -I/root/bin/php-latest/include/php/ext -I/root/bin/php-latest/include/php/ext/date/lib -I/root/parallel  -DHAVE_CONFIG_H  -g -O2   -Wall -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1  -DZEND_COMPILE_DL_EXT=1 -c /root/parallel/src/events.c -o src/events.lo  -MMD -MF src/events.dep -MT src/events.lo
 cc -I. -I/root/parallel -I/root/parallel/include -I/root/parallel/main -I/root/parallel -I/root/bin/php-latest/include/php -I/root/bin/php-latest/include/php/main -I/root/bin/php-latest/include/php/TSRM -I/root/bin/php-latest/include/php/Zend -I/root/bin/php-latest/include/php/ext -I/root/bin/php-latest/include/php/ext/date/lib -I/root/parallel -DHAVE_CONFIG_H -g -O2 -Wall -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -DZEND_COMPILE_DL_EXT=1 -c /root/parallel/src/events.c -MMD -MF src/events.dep -MT src/events.lo  -fPIC -DPIC -o src/.libs/events.o
In file included from /root/bin/php-latest/include/php/main/php.h:35,
                 from /root/parallel/src/parallel.h:21,
                 from /root/parallel/src/events.c:21:
/root/parallel/src/events.c:249:33: error: 'php_parallel_events_poll_arginfo' undeclared here (not in a function); did you mean 'php_parallel_events_count_arginfo'?
  249 |     PHP_ME(Events, poll,        php_parallel_events_poll_arginfo, ZEND_ACC_PUBLIC)
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/bin/php-latest/include/php/Zend/zend_API.h:77:80: note: in definition of macro 'ZEND_RAW_FENTRY'
   77 | #define ZEND_RAW_FENTRY(zend_name, name, arg_info, flags)   { zend_name, name, arg_info, (uint32_t) (sizeof(arg_info)/sizeof(struct _zend_internal_arg_info)-1), flags },
      |                                                                                ^~~~~~~~
/root/bin/php-latest/include/php/main/php.h:375:25: note: in expansion of macro 'ZEND_ME'
  375 | #define PHP_ME          ZEND_ME
      |                         ^~~~~~~
/root/parallel/src/events.c:249:5: note: in expansion of macro 'PHP_ME'
  249 |     PHP_ME(Events, poll,        php_parallel_events_poll_arginfo, ZEND_ACC_PUBLIC)
      |     ^~~~~~
make: *** [Makefile:243: src/events.lo] Error 1

![image](https://user-images.githubusercontent.com/52495131/158667747-1af07922-ced7-4d2e-83a4-18e57bf21b65.png)

**Comment by dixyes** [comment]
@dividerbeam seems the patch is not correctly applied? I've tried at linux with gcc 11.2.0, the patch works well with develop branch for php 8.0.3 zts.

**Comment by krakjoe** [comment]
Fixed in develop.
